Repository aslams2020/Stark-Tech-Portfolio, pull requests merged in 2024-10, with the labels that each got.

#35 Improving Overflow of Images over navbar
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#34 Changes in the alignment of the content when screen is made smaller
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#26 Update style.css
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#65 Added Detailed CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, gssoc-ext, hacktoberfest-accepted, level1

#76 made the website look dynamic
  index.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#86 Added the changes
  index.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#102 Fixed #55 : Automated Greeting Workflow
  .github/workflows/greetings.yml
Labels: gssoc-ext, hacktoberfest-accepted, level1

#108 Back to Top button
  index.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#118 Add Appearances page and added Appearance button in navbar to redirect to Appearances Page
  Appearances.css
  Appearances.html
  index.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#127 adding responsiveness in home page
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#126 video and movies updated
  assets/posters/ironmanmovie1.jpg
  assets/posters/ironmanmovie10.png
  assets/posters/ironmanmovie11.png
  assets/posters/ironmanmovie2.png
  assets/posters/ironmanmovie3.png
  assets/posters/ironmanmovie4.png
  assets/posters/ironmanmovie5.png
  assets/posters/ironmanmovie6.png
  assets/posters/ironmanmovie7.png
  assets/posters/ironmanmovie8.png
  assets/posters/ironmanmovie9.png
  index.html
  movies.html
  style.css
  videos.html
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#135 focus of cursor on loading web page is added
  index.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#137 Bug fixed #132
  index.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#149 Improved navbar links and responsive design across pages.
  Appearances.html
  Js/script.js
  css/Appearances.css
  index.html
  movies.html
  style.css
  videos.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#156 Contact page improved
  index.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#157 adding back to top button
  Appearances.html
  css/Appearances.css
  movies.html
  videos.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#113 Added Social media-icons in footer
  index.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#165 Redesigned the hero section
  assets/ironman_illustration.png
  index.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#166 Added a Custom effect in Cursor
  Appearances.html
  index.html
  movies.html
  videos.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#173 Fixed Logo Responsiveness | #109
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#192 Added Follow us on Socials in all pages
  Appearances.html
  css/Appearances.css
  index.html
  movies.html
  videos.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#187 Add footer which is crucial for navigation.
  index.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#206 add the variant section and I made the required changes issue#62
  assets/variants/IronKnight.jpg
  assets/variants/Thecrossing.jpg
  assets/variants/doctordoomironman.jpg
  assets/variants/infintywraps.jpg
  assets/variants/ironman2099.jpg
  assets/variants/ironmanaic.jpg
  assets/variants/ironmaninexiles.jpg
  assets/variants/sorcerorsupreme.jpg
  assets/variants/ultimateironman.jpg
  index.html
  style.css
  variants.css
  variants.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#228 updated the readme file.
  README.md
Labels: documentation, gssoc-ext, level1

#233 the scroll to top button has been added at the variants page !
  cropped_image.png
  variants.css
  variants.html
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level1

#243 bugs fixed in appearances and movies section
  Appearances.html
  css/Appearances.css
  movies.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#246 Updated the readme file
  README.md
  assets/GSSoC-Ext.png
  assets/hacktoberfest.jpg
  assets/hacktoberfest.png
Labels: documentation, gssoc-ext, hacktoberfest-accepted, level1

#236 Add hover effects in nav and footer
  .vscode/settings.json
  index.html
  style.css
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level1

#261 Update contact page
  index.html
  style.css
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level1

#262 appearances page logo size fix
  css/Appearances.css
Labels: bug, gssoc-ext, hacktoberfest-accepted, level1

#285 add animation and hovering color change for different social media icon
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#248 feat: add a contributers page . #241
  contributor.html
  css/contributor.css
  index.html
Labels: gssoc-ext, hacktoberfest-accepted, level3

#270 Created Privacy Policy and Terms of Service Pages and Added Links to Footer
  PrivacyPolicy.html
  Terms&Conditions.html
  css/terms.css
  index.html
Labels: gssoc-ext, hacktoberfest-accepted, level3

#296 Added stickers button and added stickers to it.
  assets/stickers/cartoon-red-yellow-robot.jpg
  assets/stickers/drawing-iron-man-character.jpg
  assets/stickers/hand-drawing-little-realistic-ironman-13.avif
  assets/stickers/iron-man-simplified-head.avif
  assets/stickers/iron-man-sticker_10.jpg
  assets/stickers/iron-man-vector-illustration-flat-2.avif
  assets/stickers/iron-man-vector-illustration3.avif
  assets/stickers/ironman-character-2-numberj_12.jpg
  assets/stickers/ironman-sticker_1141877-798.avif
  assets/stickers/ironman-sticker_2.avif
  assets/stickers/sticker-iron-man-flying-through-air.jpg
  assets/stickers/sticker-iron-man-with-glowing-eyes.jpg
  assets/stickers/sticker11.avif
  assets/stickers/sticker14.avif
  assets/stickers/sticker15.avif
  assets/stickers/sticker16-1.avif
  assets/stickers/sticker16.jpg
  assets/stickers/sticker17.jpg
  assets/stickers/sticker18.jpg
  assets/stickers/sticker19.avif
  assets/stickers/sticker20.jpg
  index.html
  sticker.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#297 foot-section
  Appearances.html
  Comics.html
  PrivacyPolicy.html
  Terms&Conditions.html
  contributor.html
  index.html
  movies.html
  style.css
  variants.css
  variants.html
  videos.html
Labels: gssoc-ext, level3

#299 added remarkable achievements section in the footer
  Achievements.html
  assets/arc-reactor.jpg
  assets/avengers-initiative.jpg
  assets/iron-man-suit-1.jpg
  assets/jarvis.jpg
  assets/stark-industries.png
  index.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#300 Added a Preloader
  arc-reactor.gif
  index.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#319 the scroll to top button has been added to both appearances and achievements page
  Achievements.html
  Appearances.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#321 Added Newsletter Feature
  Appearances.html
  index.html
  movies.html
  sticker.html
  style.css
  subscribe.css
  subscribe.html
  subscribe.js
  variants.html
  videos.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#310 footer responsiveness
  index.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#314 changes by tanishraj7
  index.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#320 Enhanced ContactUs form and added styling to movies and submit button #52
  Js/script.js
  index.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#330 header active state
  Comics.html
  index.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#318 a_index.html added
  index.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#332 Added the visitor Counter to the website
  index.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#333 Hero UI Responsivenenss
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#337 Changes made in variant and appearances section
  Appearances.html
  contributor.html
  css/Appearances.css
  variants.css
  variants.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#339 Updated the hovering effect of the nav bar.
  style.css
  variants.css
  variants.html
Labels: gssoc-ext, hacktoberfest-accepted, level1
