Repository aslams2020/Stark-Tech-Portfolio, pull requests merged in 2024-11, with the labels that each got.

#344 Added easter eggs like hidden clickable links and time based message
  Achievements.html
  Appearances.html
  Comics.html
  Js/secrets.js
  assets/Gifs/snap.gif
  assets/Gifs/thanossnap.gif
  assets/Villans/AvangersAgeOfUltron_Villans.jpg
  assets/Villans/CivilWar_Villan.jpg
  assets/Villans/Homecoming_Villan.jpg
  assets/Villans/IronMan(2008)_Villan.png
  assets/Villans/IronMan2_Villan.jpg
  assets/Villans/IronMan3_Villan.webp
  assets/Villans/TheAvangers_Villan.jpg
  assets/Villans/thanos.avif
  assets/Villans/thanosarmy.jpg
  contributor.html
  css/Appearances.css
  index.html
  movies.html
  sticker.html
  style.css
  variants.html
  videos.html
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#353 Created merchandise page and checkout page with proper functionality
  assets/merchandise/acf3.webp
  assets/merchandise/acf4_.webp
  assets/merchandise/actionfigure.webp
  assets/merchandise/actionfigure2.webp
  assets/merchandise/bottle.webp
  assets/merchandise/ironman_heart.webp
  assets/merchandise/ironman_posters.webp
  assets/merchandise/ironmanmug.webp
  assets/merchandise/jacket.webp
  assets/merchandise/jacket2.webp
  assets/merchandise/keychain.webp
  assets/merchandise/lunchbag.webp
  assets/merchandise/mask_.webp
  assets/merchandise/notebook.webp
  assets/merchandise/reactor_keychain.webp
  assets/merchandise/robot.webp
  assets/merchandise/stickers.webp
  assets/merchandise/tony_stark_poster.webp
  assets/merchandise/tshirt585.webp
  assets/merchandise/wallart.webp
  assets/merchandise/watch.webp
  checkout.html
  index.html
  merchandise.html
  sticker.html
Labels: gssoc-ext, level3

#356 Made the changes requested regarding the quiz.
  index.html
  quiz.html
Labels: gssoc-ext, level2

#355 fixed footer of privacypolicy and terms and conditions page
  Terms&Conditions.html
  css/terms.css
Labels: gssoc-ext, level1

#358 Fixed the UI/UX of Newsletter
  subscribe.css
Labels: gssoc-ext, level1

#360 Enhanced scroll back button with timeline on it for smoother functioning.
  Achievements.html
  Appearances.html
  Comics.html
  PrivacyPolicy.html
  Terms&Conditions.html
  index.html
  movies.html
  sticker.html
  variants.html
  videos.html
Labels: gssoc-ext, level2

#362 Made the changes mentioned in the previous PR.
  quiz.html
Labels: gssoc-ext, level1

#366 Added 404 page
  .htaccess
  404.css
  404.html
  index.html
Labels: gssoc-ext, level2

#295 Added Blogs Page | Issue #255
  Appearances.html
  Comics.html
  PrivacyPolicy.html
  Terms&Conditions.html
  blog.html
  contributor.html
  index.html
  movies.html
  variants.html
  videos.html
Labels: gssoc-ext, level2

#367 Added a Villain Page
  Appearances.html
  Comics.html
  Js/villain.js
  PrivacyPolicy.html
  Terms&Conditions.html
  assets/Villains/Aldrich Killian.webp
  assets/Villains/Iron_Monger.png
  assets/Villains/Justin Hammer.webp
  assets/Villains/Loki.jpg
  assets/Villains/Thanos.jpg
  assets/Villains/TheMandarin.jpg
  assets/Villains/Ultron.jpg
  assets/Villains/Whiplash.jpg
  assets/Villains/Winter_Soldier.webp
  blog.html
  contributor.html
  css/villain.css
  index.html
  villain.html
Labels: gssoc-ext, level3

#373 Make blog page responsive
  style.css
Labels: gssoc-ext, level1

#390 Fixed footer alignment
  css/Appearances.css
  css/contributor.css
  style.css
Labels: gssoc-ext, level1

#392 Fixed issue #382
  style.css
Labels: gssoc-ext, level1

#396 Text Changed
  index.html
Labels: gssoc-ext, level1

#397 Fixed issue #381
  Js/script.js
  index.html
  style.css
Labels: gssoc-ext, level1

#398 Improve Contributors page done ! #350
  contributor.html
Labels: gssoc-ext, level1

#399 the progress bar has been added to all the required pages
  Comics.html
  merchandise.html
  movies.html
  quiz.html
  sticker.html
  variants.css
  variants.html
Labels: gssoc-ext, level2

#401 Fixed Buy Merchandise Section and Added Missing Favicons
  Achievements.html
  Appearances.html
  css/merchandise.css
  merchandise.html
Labels: enhancement, level3

#403 Make video page responsive.
  videos.html
Labels: enhancement, gssoc-ext, level1

#407 Created Iron Man Wallpaper Gallery
  css/wallpaper.css
  images/desktop/desk1.jpg
  images/desktop/desk2.jpg
  images/desktop/desk3.jpg
  images/desktop/desk4.jpg
  images/laptop/lap1.jpg
  images/laptop/lap2.jpg
  images/laptop/lap3.jpg
  images/laptop/lap4.jpg
  images/laptop/lap5.jpg
  images/mobile/phon1.png
  images/mobile/phon2.png
  images/mobile/phon3.png
  images/mobile/phon4.png
  images/tablet/tab1.jpg
  images/tablet/tab2.jpg
  images/tablet/tab3.jpg
  images/tablet/tab4.jpg
  index.html
  wallpaper.html
Labels: enhancement, gssoc-ext, level3

#411 Added separate FAQs page
  FAQs.html
  index.html
Labels: gssoc-ext, level2

#414 adding checkout and add to cart options to sticker page
  checkout.html
  sticker.html
  style.css
Labels: gssoc-ext, level2

#415 Bugs fixed
  Achievements.html
  Appearances.html
  Comics.html
  PrivacyPolicy.html
  Terms&Conditions.html
  blog.html
  index.html
  merchandise.html
  movies.html
  quiz.html
  sticker.html
  style.css
  variants.css
  variants.html
  videos.html
  villain.html
Labels: bug, enhancement, gssoc-ext, level3

#412 Make Variants page responsive.
  variants.css
  variants.html
Labels: gssoc-ext, level1

#416 style.css file updated, issue number #404 is solved
  style.css
Labels: gssoc-ext, level1

#420 Bugs Fixed
  Achievements.html
  Appearances.html
  Comics.html
  PrivacyPolicy.html
  Terms&Conditions.html
  blog.html
  contributor.html
  index.html
  merchandise.html
  movies.html
  quiz.html
  sticker.html
  style.css
  variants.css
  variants.html
  videos.html
  villain.html
  wallpaper.html
Labels: bug, enhancement, gssoc-ext, level3

#421 add vote poll system in movies page
  movies.html
Labels: gssoc-ext, level3

#423 Subscribe button problem is solved, #394 issue is solved
  index.html
  style.css
Labels: enhancement, gssoc-ext, level1
